name: marveloanalytics
version: '1.0'

config-version: 2

profile: marveloanalytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marveloanalytics:
    staging:
      +schema: stg
      +materialized: table

    silver:
      +schema: slv
      +materialized: ephemeral

    gold:
      +schema: gld
      +materialized: table

    snapshots:
      +schema: snapshot
      +materialized: snapshot